### ISSUE TITLE
netdata-timescale-relay daemon command not working

### ISSUE THREAD

**Issue by tkdhanasekar** [mahlonsmith/netdata-timescale-relay#1]
installed netdata / nim / postgressql / daemon tool 
but cannot find daemon command in centos 7
could i get better doc on this

**Comment by mahlonsmith** [comment]
That was merely a suggestion for running a foreground process as a daemon, the relay is meant to just be a piece of the toolchain.  There are many packages that offer this feature (daemontools, daemonize, systemd, etc), each with their own documentation and usage specifics.

https://centos.pkgs.org/7/epel-x86_64/daemonize-1.7.7-1.el7.x86_64.rpm.html

Which you want to use and how to use it isn't specific to the netdata-timescale-relay.
