### ISSUE TITLE
How to use with grafana ?

### ISSUE THREAD

**Issue by devosalain** [mahlonsmith/netdata-timescale-relay#4]
Solved:  This works (metrics->>'apps.cpu.node')::numeric

**Comment by mahlonsmith** [comment]
Yep.  Here's a simple one for viewing memory on a FreeBSD system:

```sql
SELECT
  $__timeGroupAlias( "time", $__interval ),
  AVG( (metrics->>'mem.committed.Committed_AS')::real ) AS "In Use",
  AVG( (metrics->>'system.ram.free')::real ) AS "Available",
  AVG( (metrics->>'system.swap.used')::real ) AS "Swapped"
FROM netdata
WHERE
  host = '$Hostname' AND
  $__timeFilter("time")
GROUP BY 1
ORDER BY 1
```

Just noticed the link in the README to Timescale's JSON docs is a 404, so I'll update that for reference.

https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/json/#json
