### ISSUE TITLE
Precompiled binaries?

### ISSUE THREAD

**Issue by wavded** [mahlonsmith/netdata-timescale-relay#5]
Have you thought about providing precompiled binaries for this project?  It would help save time for those who don't have a Nim build environment.  Example:

https://github.com/h3rald/nimhttpd/releases

**Comment by wavded** [comment]
Looking more at that project, it appears they set up a workflow to handle that -> https://github.com/h3rald/nimhttpd/blob/master/.github/workflows/add-artifacts-to-current-release.yml

**Comment by mahlonsmith** [comment]
Yo!  Thanks for the comment!  Personal philosophical opinions aside, I -do- see the argument for low barrier-to-entry via binary executables, if for no other reason to get up and running faster. 

With that said, I likely won't be attaching binaries here for a few reasons:

  - Although github is the defacto winner in code hosting (for the foreseeable future, at least), this repo is technically still a mirror that exists primarily for visibility, and I'd prefer not to have github specific artifacts polluting the repo.
  - Attached binaries imply support.  In no way do I wish to support binary distributions.  (As as example, you can run this binary without having PG libs installed, which are an absolute requirement and also out of my control)
  - Ultimately, I think binaries are better served by platform specific package maintainers, who can include the proper dependencies, default configuration file locations, and optionally the platform-preferred daemonizing methodology (systemd, daemon, docker container, whatever the flavor-du-jour is.)   Options++.

If anyone cares to create a package for their operating system of choice, I'd be more than happy to add README links to them.
